  on:
    push:
      branches: [main]
    pull_request:
  name: CI
  jobs:
    flatpak:
      name: "Flatpak"
      runs-on: ubuntu-latest
      container:
        image: bilelmoussaoui/flatpak-github-actions:kde-5.15-21.08
        options: --privileged
      steps:
      - uses: actions/checkout@v2
      - uses: snickerbockers/submodules-init@v4
      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: palette.flatpak
          manifest-path: io.github.kotatogram.yml
          cache-key: flatpak-builder-${{ github.sha }}
